In [1]:
import numpy as np
np.__version__

'1.19.2'

In [2]:
# why numpy array over list

In [3]:
#Memory and time homo
from sys import getsizeof
from time import time

In [4]:
lst = list(range(1000000))
ary = np.array(range(1000000))
getsizeof(lst),getsizeof(ary)

(8000056, 4000096)

In [5]:
start = time()
lst = [i+2 for i in lst]
print(time()-start)

0.08078336715698242


In [6]:
start = time()
ary += 2
print(time()-start)

0.0009992122650146484


In [7]:
#Array

In [8]:
x = np.array([2,3,4])
x

array([2, 3, 4])

In [9]:
x = np.array([[[1,2,3,4],[2,2,3,4],[3,2,3,4]],[[2,2,3,4],[5,2,3,4],[4,2,3,4]]])
x

array([[[1, 2, 3, 4],
        [2, 2, 3, 4],
        [3, 2, 3, 4]],

       [[2, 2, 3, 4],
        [5, 2, 3, 4],
        [4, 2, 3, 4]]])

In [10]:
np.arange(0,11)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [11]:
np.arange(0,11,2)

array([ 0,  2,  4,  6,  8, 10])

In [12]:
np.arange(10,0,-1)

array([10,  9,  8,  7,  6,  5,  4,  3,  2,  1])

In [13]:
np.linspace(0,10,11)

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [14]:
np.logspace(0,10,11)

array([1.e+00, 1.e+01, 1.e+02, 1.e+03, 1.e+04, 1.e+05, 1.e+06, 1.e+07,
       1.e+08, 1.e+09, 1.e+10])

In [15]:
arryzero = np.zeros((2,3,2))
arryzero

array([[[0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.]]])

In [16]:
aryones = np.ones((4,3))
aryones

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [17]:
aryfull = np.full((4,3),8)
aryfull

array([[8, 8, 8],
       [8, 8, 8],
       [8, 8, 8],
       [8, 8, 8]])

In [18]:
a = np.ones((4,3)) * 8
a

array([[8., 8., 8.],
       [8., 8., 8.],
       [8., 8., 8.],
       [8., 8., 8.]])

In [19]:
I = np.eye(4)
I

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [20]:
np.random.rand(4,3)

array([[0.21791296, 0.82483971, 0.15289417],
       [0.83940873, 0.79346798, 0.50563476],
       [0.3027946 , 0.63281299, 0.24350562],
       [0.07621541, 0.90190484, 0.15715878]])

In [21]:
np.random.randint(0,5,(3,4))

array([[0, 0, 3, 2],
       [1, 2, 4, 2],
       [4, 3, 4, 4]])

In [22]:
np.loadtxt(fname="a.csv",delimiter=',')

array([[1., 2., 3., 4., 5.],
       [6., 5., 4., 3., 2.],
       [2., 3., 6., 7., 4.]])

In [23]:
#Array Attributes

In [24]:
x = np.random.rand(3,4,2)
x

array([[[0.157886  , 0.49376156],
        [0.13468742, 0.86969754],
        [0.33529754, 0.36274314],
        [0.11377944, 0.14762066]],

       [[0.65234066, 0.18640937],
        [0.57241277, 0.68996046],
        [0.51443387, 0.72738613],
        [0.47686115, 0.95019399]],

       [[0.29416789, 0.77423509],
        [0.74563209, 0.44610707],
        [0.78497084, 0.76102362],
        [0.75828988, 0.73076847]]])

In [25]:
x.ndim

3

In [26]:
x.shape

(3, 4, 2)

In [27]:
x.dtype

dtype('float64')

In [28]:
x.size

24

In [29]:
from sys import getsizeof

In [30]:
getsizeof(x)

320

In [31]:
x.nbytes

192

In [32]:
#array transformation

In [33]:
a = np.arange(12)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [34]:
b = a.reshape(3,4)
b

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [35]:
a.resize(6,2)
a

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11]])

In [36]:
a = a.flatten()
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [37]:
b.transpose()

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

In [38]:
a.resize(6,2)
a.transpose()

array([[ 0,  2,  4,  6,  8, 10],
       [ 1,  3,  5,  7,  9, 11]])

In [39]:
#hstack,vstack

In [40]:
a = np.random.randint(0,10,(4,2))
b = np.random.randint(0,10,(4,2))
np.vstack((a,b))

array([[0, 1],
       [0, 1],
       [0, 0],
       [9, 3],
       [6, 7],
       [0, 9],
       [0, 4],
       [3, 7]])

In [41]:
np.hstack((a,b))

array([[0, 1, 6, 7],
       [0, 1, 0, 9],
       [0, 0, 0, 4],
       [9, 3, 3, 7]])

In [42]:
data = np.loadtxt(fname = "data.csv",delimiter = ',')
print(data)
data.ndim,data.shape,data.size,data.dtype

[[ 1. 52. 37.  4.  5.  6. 77.  8.  9.  0.]
 [12.  2. 33.  4. 52.  6.  7. 84.  9.  0.]
 [ 1.  2.  3.  4.  5.  6.  7. 82. 39.  0.]
 [51.  2.  3. 14. 45.  6. 71.  8.  9.  0.]
 [91. 72. 31.  4.  5.  6.  7.  8.  9. 40.]
 [19. 32. 33. 14.  5.  6.  7.  8. 94.  0.]
 [ 1. 27.  3. 43.  5.  6. 74.  8.  9.  0.]
 [41. 52. 23.  4. 51. 64. 37.  8. 39. 50.]
 [15. 32.  3.  4. 45.  6. 71.  8.  9.  0.]
 [16. 29.  3.  4. 54.  6. 74. 81.  9. 20.]]


(2, (10, 10), 100, dtype('float64'))

In [43]:
data[0][1],data[0,1]

(52.0, 52.0)

In [44]:
data[-1,-1]

20.0

In [45]:
data[0:4,3:5]

array([[ 4.,  5.],
       [ 4., 52.],
       [ 4.,  5.],
       [14., 45.]])

In [46]:
data[3:5,0:5]

array([[51.,  2.,  3., 14., 45.],
       [91., 72., 31.,  4.,  5.]])

In [47]:
k = data[data>80]
k[k<90]

array([84., 82., 81.])

In [48]:
k

array([84., 82., 91., 94., 81.])

In [49]:
#Addition subtraction
k - 80

array([ 4.,  2., 11., 14.,  1.])

In [54]:
#Multiplication Division
(k -80 )* 10

array([ 40.,  20., 110., 140.,  10.])

In [56]:
#Linear Algebra

In [67]:
a = np.random.rand(2,3)
b = np.random.rand(3,2)
a,b

a = np.matmul(a,b)
a

array([[0.71714677, 0.1625812 ],
       [0.67801904, 0.22517045]])

In [68]:
np.linalg.det(a)
np.linalg.eigvals(a)

array([0.88436961, 0.05794761])

In [69]:
#Stats

In [70]:
b

array([[2.08923386e-01, 2.37712521e-01],
       [5.39795021e-01, 3.55553862e-04],
       [4.80941069e-01, 1.31338607e-01]])

In [72]:
b.max()

0.5397950211254712

In [73]:
np.max(b)

0.5397950211254712

In [74]:

np.max(b[0:1])

0.2377125209271046

In [78]:
print(b)
np.min(b,axis = 1)

[[2.08923386e-01 2.37712521e-01]
 [5.39795021e-01 3.55553862e-04]
 [4.80941069e-01 1.31338607e-01]]


array([0.20892339, 0.00035555, 0.13133861])

In [80]:
np.min(b,axis = 0)

array([0.20892339, 0.00035555])

In [82]:
np.mean(b,axis=0)

array([0.40988649, 0.12313556])

In [83]:
np.std(b)

0.18882107651766872