In [1]:
import numpy as np
np.__version__

'1.19.2'

In [2]:
# why numpy array over list

In [3]:
#Memory and time homo
from sys import getsizeof
from time import time

In [4]:
lst = list(range(1000000))
ary = np.array(range(1000000))
getsizeof(lst),getsizeof(ary)

(8000056, 4000096)

In [5]:
start = time()
lst = [i+2 for i in lst]
print(time()-start)

0.07880449295043945


In [6]:
start = time()
ary += 2
print(time()-start)

0.0009927749633789062


In [7]:
#Array

In [8]:
x = np.array([2,3,4])
x

array([2, 3, 4])

In [15]:
x = np.array([[[1,2,3,4],[2,2,3,4],[3,2,3,4]],[[2,2,3,4],[5,2,3,4],[4,2,3,4]]])
x

array([[[1, 2, 3, 4],
        [2, 2, 3, 4],
        [3, 2, 3, 4]],

       [[2, 2, 3, 4],
        [5, 2, 3, 4],
        [4, 2, 3, 4]]])

In [16]:
np.arange(0,11)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [17]:
np.arange(0,11,2)

array([ 0,  2,  4,  6,  8, 10])

In [19]:
np.arange(10,0,-1)

array([10,  9,  8,  7,  6,  5,  4,  3,  2,  1])

In [30]:
np.linspace(0,10,11)

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [33]:
np.logspace(0,10,11)

array([1.e+00, 1.e+01, 1.e+02, 1.e+03, 1.e+04, 1.e+05, 1.e+06, 1.e+07,
       1.e+08, 1.e+09, 1.e+10])

In [36]:
arryzero = np.zeros((2,3,2))
arryzero

array([[[0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.]]])

In [41]:
aryones = np.ones((4,3))
aryones

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [49]:
aryfull = np.full((4,3),8)
aryfull

array([[8, 8, 8],
       [8, 8, 8],
       [8, 8, 8],
       [8, 8, 8]])

In [50]:
a = np.ones((4,3)) * 8
a

array([[8., 8., 8.],
       [8., 8., 8.],
       [8., 8., 8.],
       [8., 8., 8.]])

In [51]:
I = np.eye(4)
I

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [52]:
np.random.rand(4,3)

array([[0.50486053, 0.54552843, 0.93971389],
       [0.57131592, 0.13801317, 0.31998203],
       [0.76640278, 0.77050092, 0.45278915],
       [0.06106607, 0.56537643, 0.06405293]])

In [54]:
np.random.randint(0,5,(3,4))

array([[4, 2, 2, 2],
       [1, 0, 3, 3],
       [2, 4, 2, 4]])

In [57]:
np.loadtxt(fname="a.csv",delimiter=',')

array([[1., 2., 3., 4., 5.],
       [6., 5., 4., 3., 2.],
       [2., 3., 6., 7., 4.]])

In [58]:
#Array Attributes

In [64]:
x = np.random.rand(3,4,2)
x

array([[[0.98776696, 0.9688338 ],
        [0.3970112 , 0.59857401],
        [0.34115592, 0.19060181],
        [0.97477256, 0.61534435]],

       [[0.15070302, 0.16732524],
        [0.65781725, 0.38208439],
        [0.96881274, 0.35154338],
        [0.34707847, 0.1623713 ]],

       [[0.31287274, 0.78349   ],
        [0.75601177, 0.597504  ],
        [0.15608914, 0.63922429],
        [0.84675545, 0.11810542]]])

In [65]:
x.ndim

3

In [66]:
x.shape

(3, 4, 2)

In [67]:
x.dtype

dtype('float64')

In [68]:
x.size

24

In [69]:
from sys import getsizeof

In [70]:
getsizeof(x)

320

In [71]:
x.nbytes

192

In [73]:
#array transformation

In [89]:
a = np.arange(12)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [90]:
b = a.reshape(3,4)
b

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [91]:
a.resize(6,2)
a

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11]])

In [92]:
a = a.flatten()
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [93]:
b.transpose()

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

In [95]:
a.resize(6,2)
a.transpose()

array([[ 0,  2,  4,  6,  8, 10],
       [ 1,  3,  5,  7,  9, 11]])

In [96]:
#hstack,vstack

In [102]:
a = np.random.randint(0,10,(4,2))
b = np.random.randint(0,10,(4,2))
np.vstack((a,b))

array([[7, 9],
       [5, 8],
       [3, 9],
       [0, 7],
       [7, 6],
       [9, 2],
       [8, 0],
       [7, 9]])

In [103]:
np.hstack((a,b))

array([[7, 9, 7, 6],
       [5, 8, 9, 2],
       [3, 9, 8, 0],
       [0, 7, 7, 9]])

In [114]:
data = np.loadtxt(fname = "data.csv",delimiter = ',')
print(data)
data.ndim,data.shape,data.size,data.dtype

[[ 1. 52. 37.  4.  5.  6. 77.  8.  9.  0.]
 [12.  2. 33.  4. 52.  6.  7. 84.  9.  0.]
 [ 1.  2.  3.  4.  5.  6.  7. 82. 39.  0.]
 [51.  2.  3. 14. 45.  6. 71.  8.  9.  0.]
 [91. 72. 31.  4.  5.  6.  7.  8.  9. 40.]
 [19. 32. 33. 14.  5.  6.  7.  8. 94.  0.]
 [ 1. 27.  3. 43.  5.  6. 74.  8.  9.  0.]
 [41. 52. 23.  4. 51. 64. 37.  8. 39. 50.]
 [15. 32.  3.  4. 45.  6. 71.  8.  9.  0.]
 [16. 29.  3.  4. 54.  6. 74. 81.  9. 20.]]


(2, (10, 10), 100, dtype('float64'))

In [119]:
data[0][1],data[0,1]

(52.0, 52.0)

In [120]:
data[-1,-1]

20.0

In [124]:
data[0:4,3:5]

array([[ 4.,  5.],
       [ 4., 52.],
       [ 4.,  5.],
       [14., 45.]])

In [128]:
data[3:5,0:5]

array([[51.,  2.,  3., 14., 45.],
       [91., 72., 31.,  4.,  5.]])

In [140]:
k = data[data>80]
k[k<90]

array([84., 82., 81.])